#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AHK_SRC="$REPO_ROOT/clipboard-splash.ahk"

# This wizard changes Windows state rather than collecting values, so it uses
# none of the .env / gh helpers above. Everything goes through one PowerShell
# helper written to a temp file, which keeps bash out of PowerShell quoting.
PS1_FILE="$(mktemp -t winc-helper-XXXXXX.ps1)"
trap 'rm -f "$PS1_FILE"' EXIT

cat > "$PS1_FILE" <<'PSEOF'
param([string]$Action, [string]$Arg)

$APP    = "$env:LOCALAPPDATA\Clipboard Splash\clipboard-splash.exe"
$POLICY = "HKCU:\Software\Policies\Microsoft\Windows\WindowsCopilot"
$AHKS   = @(
  "$env:ProgramFiles\AutoHotkey\v2\AutoHotkey64.exe",
  "$env:ProgramFiles\AutoHotkey\v2\AutoHotkey32.exe",
  "${env:ProgramFiles(x86)}\AutoHotkey\v2\AutoHotkey64.exe",
  "$env:LOCALAPPDATA\Programs\AutoHotkey\v2\AutoHotkey64.exe"
)

Add-Type @'
using System;
using System.Runtime.InteropServices;
public class WinC {
  [DllImport("user32.dll", SetLastError=true)]
  public static extern bool RegisterHotKey(IntPtr h, int id, uint mods, uint vk);
  [DllImport("user32.dll")]
  public static extern bool UnregisterHotKey(IntPtr h, int id);
}
'@

function Find-Ahk { foreach ($c in $AHKS) { if (Test-Path $c) { return $c } } return "" }

# MOD_WIN = 0x8, VK_C = 0x43. If anything already owns Win+C the call fails
# with ERROR_HOTKEY_ALREADY_REGISTERED (1409).
function Probe {
  $ok  = [WinC]::RegisterHotKey([IntPtr]::Zero, 3141, 0x8, 0x43)
  $err = [Runtime.InteropServices.Marshal]::GetLastWin32Error()
  if ($ok) { [WinC]::UnregisterHotKey([IntPtr]::Zero, 3141) | Out-Null; return "FREE" }
  if ($err -eq 1409) { return "TAKEN" }
  return "ERROR:$err"
}

switch ($Action) {
  "probe" { Probe }

  "appstate" {
    $running = $null -ne (Get-Process clipboard-splash -ErrorAction SilentlyContinue)
    "INSTALLED:$(Test-Path $APP) RUNNING:$running"
  }

  "ahkpath" { Find-Ahk }

  "policystate" {
    if (Test-Path $POLICY) {
      $v = (Get-ItemProperty $POLICY -ErrorAction SilentlyContinue).TurnOffWindowsCopilot
      if ($null -ne $v) { "SET:$v" } else { "KEY_NO_VALUE" }
    } else { "NONE" }
  }

  # Relaunches this same script elevated. An elevation of the same user keeps
  # the same HKCU hive, so the policy lands on the right account.
  "policy" {
    try {
      $p = Start-Process powershell -Verb RunAs -Wait -PassThru -ArgumentList @(
        "-NoProfile","-ExecutionPolicy","Bypass","-File","`"$PSCommandPath`"","-Action","writepolicy"
      )
      "ELEVATED_EXIT:$($p.ExitCode)"
    } catch { "DECLINED" }
  }

  "writepolicy" {
    if (-not (Test-Path $POLICY)) { New-Item -Path $POLICY -Force | Out-Null }
    New-ItemProperty -Path $POLICY -Name TurnOffWindowsCopilot -Value 1 -PropertyType DWord -Force | Out-Null
  }

  "explorer" {
    Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 3
    if (-not (Get-Process explorer -ErrorAction SilentlyContinue)) { Start-Process explorer.exe }
    Start-Sleep -Seconds 2
    "RESTARTED"
  }

  "stopapp" {
    Stop-Process -Name clipboard-splash -Force -ErrorAction SilentlyContinue
    Start-Sleep -Milliseconds 800
    "STOPPED"
  }

  "startapp" {
    if (Test-Path $APP) { Start-Process $APP; Start-Sleep -Seconds 3; "STARTED" }
    else { "MISSING" }
  }

  "ahkinstall" {
    $ahk = Find-Ahk
    if (-not $ahk) { "NO_AHK" }
    elseif (-not (Test-Path $Arg)) { "NO_SCRIPT" }
    else {
      $dest = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\clipboard-splash.ahk"
      Copy-Item -LiteralPath $Arg -Destination $dest -Force
      Start-Process -FilePath $ahk -ArgumentList "`"$dest`""
      Start-Sleep -Seconds 2
      "OK:$dest"
    }
  }

  default { "UNKNOWN_ACTION" }
}
PSEOF

PS1_WIN="$(cygpath -w "$PS1_FILE" 2>/dev/null || printf '%s' "$PS1_FILE")"

# psh ACTION [ARG] -> helper stdout, CR stripped. Never aborts the wizard, so
# a failed probe gets reported rather than killing the run under `set -e`.
psh() {
  local action="$1" arg="${2:-}"
  powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$PS1_WIN" \
    -Action "$action" -Arg "$arg" 2>/dev/null | tr -d '\r' || true
}

# The library banner talks about browsers and copied values; neither applies
# here, so this wizard opens with its own framing rather than calling banner().
_clear
printf '\n%s%s  Give Win+C to Clipboard Splash%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
printf '%s  Windows reserves Win+C for Copilot and RegisterHotKey refuses it. This\n' "$DIM"
printf '  wizard turns Copilot off (one elevated step only you can approve), then\n'
printf '  checks whether the key came free. If it did not, it falls back to an\n'
printf '  AutoHotkey hook that works either way.\n\n'
printf '  Nothing here is destructive, and every check reads live system state,\n'
printf '  so re-running after a sign-out is safe.%s\n' "$RESET"
pause "Ready to start?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Reading current state. Nothing changes in this stage."
printf '\n'

APP_STATE="$(psh appstate)"
AHK_EXE="$(psh ahkpath)"
POLICY_STATE="$(psh policystate)"
OWNER_BEFORE="$(psh probe)"

note "Clipboard Splash : $APP_STATE"
note "AutoHotkey v2    : ${AHK_EXE:-not found}"
note "Copilot policy   : $POLICY_STATE"
note "Win+C right now  : $OWNER_BEFORE"
printf '\n'

case "$APP_STATE" in
  *INSTALLED:True*) ;;
  *)
    warn "Clipboard Splash is not installed at the expected path."
    say  "Run 'pnpm tauri build', then the installer under"
    note "src-tauri/target/release/bundle/nsis/, and re-run this wizard."
    exit 1
    ;;
esac

if [[ "$OWNER_BEFORE" == "FREE" ]]; then
  say "Win+C is already free; stages 2 and 3 will be quick."
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Turn off Copilot (needs your approval)"
if [[ "$POLICY_STATE" == "SET:1" ]]; then
  say "Already set, nothing to do here."
  note "TurnOffWindowsCopilot = 1"
  pause
else
  say "This writes a single registry value:"
  note "HKCU\\Software\\Policies\\Microsoft\\Windows\\WindowsCopilot"
  note "TurnOffWindowsCopilot = 1  (DWORD)"
  printf '\n'
  say "Windows ACLs that key to administrators, which is the only reason this"
  say "needs elevation. A UAC prompt will appear."
  printf '\n'
  step "Approve the UAC prompt when it appears."
  pause "Press Enter to trigger it"

  RESULT="$(psh policy)"
  POLICY_STATE="$(psh policystate)"
  printf '\n'
  if [[ "$POLICY_STATE" == "SET:1" ]]; then
    printf '  %s✓%s policy written (TurnOffWindowsCopilot = 1)\n' "$GREEN" "$RESET"
  else
    warn "policy not set ($RESULT); you may have declined the prompt"
    SKIPPED+=("Copilot policy: re-run this wizard and approve the UAC prompt")
  fi
  pause
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Restart Explorer and retest Win+C"
say "The shell grabs Win+C when it starts, so it has to restart before the"
say "policy can change anything."
printf '\n'
warn "This closes open File Explorer windows and blinks the taskbar."
note "Your other applications are unaffected."
printf '\n'

if confirm "Restart Explorer now?"; then
  psh explorer >/dev/null
  printf '  %s✓%s Explorer restarted\n' "$GREEN" "$RESET"
else
  say "Skipped. Sign out and back in later, then re-run this wizard."
  SKIPPED+=("Explorer restart or sign-out, to apply the Copilot policy")
fi

OWNER_AFTER="$(psh probe)"
printf '\n'
note "Win+C now: $OWNER_AFTER"
if [[ "$OWNER_AFTER" == "FREE" ]]; then
  printf '  %s✓%s the shell let go of Win+C\n' "$GREEN" "$RESET"
else
  warn "the shell still holds Win+C; stage 5 will cover it"
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Hand Win+C to Clipboard Splash"
say "Restarting the app so it can claim the key, then proving that it did."
printf '\n'

psh stopapp >/dev/null
FREE_WITHOUT_APP="$(psh probe)"
note "app stopped, Win+C is: $FREE_WITHOUT_APP"

psh startapp >/dev/null
OWNED_WITH_APP="$(psh probe)"
note "app running, Win+C is: $OWNED_WITH_APP"
printf '\n'

APP_HAS_WINC=no
if [[ "$FREE_WITHOUT_APP" == "FREE" && "$OWNED_WITH_APP" == "TAKEN" ]]; then
  APP_HAS_WINC=yes
  printf '  %s✓%s free without the app, taken with it, so the app owns Win+C.\n' "$GREEN" "$RESET"
  say "No AutoHotkey needed."
else
  warn "the app could not claim Win+C"
  note "Win+Alt+C and Ctrl+Alt+V keep working regardless."
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "AutoHotkey fallback"
if [[ "$APP_HAS_WINC" == "yes" ]]; then
  say "Not needed, the app already owns Win+C natively. Skipping."
  pause
elif [[ -z "$AHK_EXE" ]]; then
  warn "AutoHotkey v2 not found, so this fallback cannot run."
  SKIPPED+=("Install AutoHotkey v2, then re-run this wizard")
  pause
else
  say "The AutoHotkey keyboard hook runs ahead of the shell, so it sees Win+C"
  say "before Copilot does. This copies the script into Startup and runs it."
  printf '\n'
  note "from: $AHK_SRC"
  note "to:   Start Menu\\Programs\\Startup\\clipboard-splash.ahk"
  note "Binds only Win+C, so it will not clash with other AutoHotkey scripts."
  printf '\n'
  if confirm "Install and start it?"; then
    AHK_SRC_WIN="$(cygpath -w "$AHK_SRC" 2>/dev/null || printf '%s' "$AHK_SRC")"
    OUT="$(psh ahkinstall "$AHK_SRC_WIN")"
    case "$OUT" in
      OK:*)
        printf '  %s✓%s installed and running\n' "$GREEN" "$RESET"
        note "${OUT#OK:}"
        ;;
      NO_SCRIPT)
        warn "clipboard-splash.ahk not found at $AHK_SRC"
        SKIPPED+=("Copy clipboard-splash.ahk into shell:startup by hand")
        ;;
      *)
        warn "could not install the script ($OUT)"
        SKIPPED+=("Copy clipboard-splash.ahk into shell:startup by hand")
        ;;
    esac
  else
    say "Skipped."
    SKIPPED+=("AutoHotkey fallback, needed for Win+C to work")
  fi
  pause
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Final state:"
printf '\n'
note "Copilot policy  : $(psh policystate)"
note "Win+C ownership : $(psh probe)"
note "App             : $(psh appstate)"
printf '\n'

if [[ "$APP_HAS_WINC" == "yes" ]]; then
  printf '  %s✓%s Win+C opens Clipboard Splash natively.\n' "$GREEN" "$RESET"
else
  step "Press Win+C now to check the AutoHotkey route is live."
  printf '\n'
  note "If Copilot still opens, sign out and back in, then re-run this wizard:"
  note "the policy only fully applies to a fresh session."
fi
printf '\n'
say "Win+Alt+C and Ctrl+Alt+V work either way."
pause "Press Enter for the summary"

finish
